language: csharp
os: linux # Ubuntu 14.04
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-003121

install:
  - dotnet restore

script:
  - dotnet build ./test/CoreMatchers.Tests/project.json