version: 0.0.1-{build}
image: Visual Studio 2015
configuration: Release
platform: Any CPU
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
build_script:
- ps: >-
    dotnet restore

    dotnet build -c Release --version-suffix alpha-$Env:APPVEYOR_BUILD_NUMBER src\CoreMatchers\project.json

    dotnet pack -c Release --version-suffix alpha-$Env:APPVEYOR_BUILD_NUMBER -o Artifacts src\CoreMatchers\project.json
test_script:
- ps: dotnet test test\CoreMatchers.Tests\project.json
artifacts:
- path: .\Artifacts\CoreMatchers.*.nupkg
  name: CoreMatchers
deploy:
- provider: NuGet
  api_key:
    secure: ioMFyLBW4dMCoxw6mxAJ30minKSdQLpVqpPzp7kzi/k0oRo+uk/mnSZkUrzY3MWZ
  skip_symbols: true
  on:
    branch: master
notifications:
- provider: Slack
  incoming_webhook: 
	secure: qjE9ayhx0NUs2PJH4VyXhhswzWonX6mMza4DMQ6jJsZVHHdgT3b1R1P6V0AEuc4EKR4tzPeAsuQjIKE3VQ82kNr60ZJEaTqapMdeIb94tPs=